# Generated by Django 4.2.11 on 2026-04-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.SlugField(help_text="Unique slug, e.g. 'greenfield' → greenfield.eduverse.com", max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('currency', models.CharField(default='KES', help_text='ISO currency: KES, NGN, GHS, UGX…', max_length=10)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('plan', models.CharField(choices=[('trial', 'Free Trial'), ('basic', 'Basic'), ('premium', 'Premium')], default='trial', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
