worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream web {
        server web:8000;
    }

    server {
        listen 80;
        # Wildcard subdomain listener for multi-tenancy
        server_name localhost *.localhost *.eduverse.com; 

        client_max_body_size 50M;

        location /static/ {
            alias /app/staticfiles/;
        }

        location /media/ {
            alias /app/media/;
        }

        location / {
            proxy_pass http://web;
            proxy_set_header Host $http_host; # Essential for TenantMiddleware
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
